name: Upload Lua script to release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  upload-asset:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Upload tag-replace.lua
        uses: actions/upload-artifact@v7
        with:
          path: ./tag-replace.lua
